<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class forumnonaktif extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('forumnonaktif_model');
        $this->load->library('form_validation');
        $this->load->library(array('PHPExcel','PHPExcel/IOFactory'));
        $this->load->helper(array('form', 'url'));
        
    }

    public function index()
    {
        $forumnonaktif = $this->forumnonaktif_model->getforumnonaktifbysekolah($this->session->userdata('id'));

        $data = array(
            
            'forumnonaktif_data' => $forumnonaktif
        );

        $this->template->load('templatep','forumnonaktif_list', $data);
        //$this->template->load('template','uu',$data);
        // $this->load->model('forumnonaktif_model');
        // $data['forumnonaktif_data'] = $this->forumnonaktif_model->get_all_forumnonaktif();
        // $this->template->load('templatep','forumnonaktif_list', $data);
    }

    public function read($id) 
    {
        $row = $this->forumnonaktif_model->get_by_id($id);
        if ($row) {
            $data = array(
        		'idForum' => $row->idForum,
        		'password' => $row->password,
        		'kodeguru' => $row->kodeguru,
        		'idSklh' => $row->idSklh,
        		'nama' => $row->nama,
            'kelas' => $row->kelas,
            'mp' => $row->mp,
       );
            $this->template->load('templatep','forumnonaktif_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('forumnonaktif'));
        }
    }

   

    
    
   
public function _ruless() 
    {
      $this->form_validation->set_rules('idForum', 'idForum', 'trim|required|xss_clean');
  $this->form_validation->set_rules('password', 'password', 'trim|required|xss_clean');
  $this->form_validation->set_rules('kodeguru', 'kodeguru', 'trim|required|xss_clean');
  $this->form_validation->set_rules('idSklh', 'idSklh', 'trim|required|xss_clean');
  $this->form_validation->set_rules('nama', 'nama', 'trim|required|xss_clean');
  $this->form_validation->set_rules('kelas', 'kelas', 'trim|required|xss_clean');
  $this->form_validation->set_rules('mp', 'mp', 'trim|required|xss_clean');
  
  $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function _rules() 
    {
      $this->form_validation->set_rules('idForum', 'idForum', 'trim|required|xss_clean|callback_valid_id');
	$this->form_validation->set_rules('password', 'password', 'trim|required|xss_clean');
	$this->form_validation->set_rules('kodeguru', 'kodeguru', 'trim|required|xss_clean');
	$this->form_validation->set_rules('idSklh', 'idSklh', 'trim|required|xss_clean');
	$this->form_validation->set_rules('nama', 'nama', 'trim|required|xss_clean');
  $this->form_validation->set_rules('kelas', 'kelas', 'trim|required|xss_clean');
  $this->form_validation->set_rules('mp', 'mp', 'trim|required|xss_clean');
  
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    

    
    
  




}

/* End of file Buku.php */
/* Location: ./application/controllers/Buku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */