<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class forum_model extends CI_Model
{

    public $table = 'forum';
    public $table2 = 'historyforum';
    public $id = 'idForum';
    public $order = 'DESC';
    public $id2 = 'idSklh';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
        // $data = $this->db->query('select * from guru join kodeguru on guru.idSklh=kodeguru.idSklh');
        // return $data;
    }
    

     function getforumbysekolah($id_sekolah){
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->where('idSklh', $id_sekolah);
        $query = $this->db->get();
        return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    
   
   

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */