<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Guru_model extends CI_Model
{

    public $table = 'guru';
    public $id = 'kodeguru';
    public $order = 'DESC';
   

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        //$this->db->where($this->id2, $id2);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
        // $guru = $this->db->query('select * from guru where idSklh="'.$idSklh.'" ');
        // return $guru;
        
    }
    function get_all_guru()
    {
        $query = $this->db->query('select * from guru join user using (idSklh)');
        return $query->result();
        
    }
    function getgurubysekolah($id_sekolah){
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->where('idSklh', $id_sekolah);
        $query = $this->db->get();
        return $query->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
  

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    
    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function create_data($data)
    {
        $this->db->insert($this->table, $data);
        if($this->db->affected_rows() > 0){
            return true;
        } else{
            return false;
        }
    }
        function valid_id($id)
    {
        $query = $this->db->get_where($this->table, array('kodeguru' => $id));
        if ($query->num_rows() > 0)
        {
            return TRUE;
        }
        else
        {
            return FALSE;
        }
    }

    //  function dd_tempat()
    // {
    //     // ambil data dari db
    //     $this->db->order_by('tempat', 'asc');
    //     $result = $this->db->get('tempat');
        
    //     // bikin array
    //     // please select berikut ini merupakan tambahan saja agar saat pertama
    //     // diload akan ditampilkan text please select.
    //     $dd[''] = 'Please Select';
    //     if ($result->num_rows() > 0) {
    //         foreach ($result->result() as $row) {
    //         // tentukan value (sebelah kiri) dan labelnya (sebelah kanan)
    //             $dd[$row->id_tempat] = $row->tempat;
    //         }
    //     }
    //     return $dd;
    // }
   

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */